"use client";

//  arey mowa koni values work katle ra like m-32 ivi asal effect a chupisthale???
// ekda chupi follow chesta agu  DHOme pa

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import DHome from "~/components/DHome";
const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({
    text: "world",
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-custom-gradient h-[667px]">
        <DHome/>
      </main>
    </>
  );
};

export default Home;
